/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Scott VanArsdale (https://sketchfab.com/vanart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/golf-ball-b0b50a16aa5d431e8ed799c1a413025c
Title: Golf Ball
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import golfBall from "../assets/3D/golf_ball.glb";

const Golfball = (props) => {
  const golfBallRef = useRef();  
  const { nodes, materials } = useGLTF(golfBall);
  return (
    <a.group {...props} ref={golfBallRef}>
      <a.group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
        //   castShadow
        //   receiveShadow
          geometry={nodes.defaultMaterial.geometry}
          material={materials.initialShadingGroup}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </a.group>
    </a.group>
  );
}

export default Golfball;
